apiVersion: v1
kind: Namespace
metadata:
  name: dev

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: SC-AllowVolumeExpansion
  namespace: dev
parameters:
  type: pd-standard
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
reclaimPolicy: Delete

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-red-webapp
  namespace: dev
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: SC-AllowVolumeExpansion
  hostPath:
    path: "/webdata-pv"
    type: Directory

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blue-webapp
  namespace: dev
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: SC-AllowVolumeExpansion
  hostPath:
    path: "/webdata2-pv"
    type: Directory

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-red-webapp
  namespace: dev
spec:
  storageClassName: SC-AllowVolumeExpansion
  resources:
    requests:
      storage: 600Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blue-webapp
  namespace: dev
spec:
  storageClassName: SC-AllowVolumeExpansion
  resources:
    requests:
      storage: 600Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-webapp-deployment
  namespace: dev
  labels:
    app: web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:      
      labels:
        app: web
        version: 22-04-2022
    spec:
      containers:
        - name: simple-webapp-color-red
          image: mmumshad/simple-webapp-color
          resources:
           limits:
             memory: "2Gi"
             cpu: "600m"
          env:
          - name: APP_COLOR
            value: red
          ports:
          - containerPort: 8080
          volumeMounts:
          - mountPath: /opt
            name: webdata-volume
      volumes:
        - name: webdata-volume
          persistentVolumeClaim:
            claimName: pvc-red-webapp

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-webapp-deployment
  namespace: dev
  labels:
    app: web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:      
      labels:
        app: web
        version: 22-04-2022
    spec:
      containers:
        - name: simple-webapp-color-blue
          image: mmumshad/simple-webapp-color
          resources:
           limits:
             memory: "2Gi"
             cpu: "600m"
          env:
          - name: APP_COLOR
            value: blue
          ports:
          - containerPort: 8080
          volumeMounts:
          - mountPath: /opt
            name: webdata2-volume
      volumes:
        - name: webdata2-volume
          persistentVolumeClaim:
            claimName: pvc-blue-webapp

---

apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: cleotest-service
spec:
  type: NodePort
  selector: 
    app: web
  ports:
  - targetPort: 8080
    port: 8080
    nodePort: 30008

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cleotest-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: cleodevtest.cleonet.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cleotest-service
                port:
                  number: 8080

