apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-volume
  template:
    metadata:
      labels:
        app: mysql-volume
    spec:
      containers:
      - name: mysql-volume
        image: mysql
        resources:
          limits:
            memory: "2Gi"
            cpu: "800m"
        env:
        - name: MYSQL_DATABASE
          value: eazytraining
        - name: MYSQL_USER
          value: eazy
        - name: MYSQL_PASSWORD
          value: eazy
        - name: MYSQL_ROOT_PASSWORD
          value: password
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-data
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mypvc
