apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: webapp-service

spec:
  type: NodePort
  selector: 
    app: web
  ports:
  - targetPort: 8080
    port: 8080
    nodePort: 30008
